# -*- coding: utf-8 -*-
"""HR data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxhsylWsd_otRsgEmWYg1Kyob43gNuSC
"""

#pip install --upgeade seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns
import missingno as msno

df = pd.read_csv("/HR Data.csv")
df.head()

!pip install sweetviz

import sweetviz
myreport = sweetviz.analyze(df)
myreport.show_notebook()

df.info()

df.isna().sum()

msno.matrix(df)

"""Eliminating redundant entries."""

df = df.drop(columns = ['StockOptionLevel'])

df.columns

"""Now as per project requirement I should eleminate Nan values, rename columns and get rid of unneccessary column. But after EDA we can see there is no requirment of renaming column as exisiting names are selfexplainatory and there are no Nan values preset in data. So now we can proceed with further analysis.

Univeriate analysis using distribution plot
"""

sns.kdeplot(df['Age'],shade=True, color = '#ff4125')

"""Similarly we can d this for all imp numerical data, or we plot simple distplot"""

sns.distplot(df['Age'])

fig, ax = plt.subplots(5,2, figsize=(9,9))
sns.distplot(df['TotalWorkingYears'], ax = ax[0,0])
sns.distplot(df['MonthlyIncome'], ax = ax[0,1])
sns.distplot(df['YearsAtCompany'], ax = ax[1,0])
sns.distplot(df['DistanceFromHome'], ax = ax[1,1])
sns.distplot(df['YearsInCurrentRole'], ax = ax[2,0])
sns.distplot(df['YearsWithCurrManager'], ax = ax[2,1])
sns.distplot(df['YearsSinceLastPromotion'], ax = ax[3,0])
sns.distplot(df['PercentSalaryHike'], ax = ax[3,1])
sns.distplot(df['YearsSinceLastPromotion'], ax = ax[4,0])
sns.distplot(df['TrainingTimesLastYear'], ax = ax[4,1])
plt.tight_layout()
plt.show()

"""Now letus analyse categorical column"""

cat_df = df.select_dtypes(include='object')
cat_df.columns

def plot_cat(attr, labels=None):
  if(attr == 'JobRole'):
    sns.catplot(data=df,kind='count',height=5, aspect=3, x=attr)
    return

  sns.catplot(data=df, kind='count', height=5, aspect=1.5, x=attr)

plot_cat('Attrition')

plot_cat('BusinessTravel')

plot_cat('EducationField')

plot_cat('Gender')

plot_cat('JobRole')

plot_cat('MaritalStatus')

plot_cat('OverTime')

"""Feature Selection
- Plotting fetaures against target value(Attrition)

"""

sns.catplot(data = df, y='Age', x ='Attrition', aspect=1, kind='box')

"""Note that the median as well the maximum age of the peole with 'No' attrition is higher than that of the 'Yes' category. This shows that peole with higher age have lesser tendency to leave the organisation which makes sense as they may have settled in the organisation.

Department
- Note that both Attrition(Target) as well as the Deaprtment are categorical. In such cases a cross-tabulation is the most reasonable way to analyze the trends; which shows clearly the number of observaftions for each class which makes it easier to analyze the results.
"""

df.Department.value_counts()

sns.catplot(data=df, kind='count', x='Attrition', col='Department')

pd.crosstab(columns=[df.Attrition], index=[df.Department], margins=True, normalize='index')

"""So from above finding from plot graph and crosstab we see that only 16% of empoyees opted for attrition while 83% percent employees opted "NO".

Gender
"""

pd.crosstab(columns=[df.Attrition], index=[df.Gender], margins=True, normalize='index')

"""About 85 % of females want to stay in the organisation while only 15 % want to leave the organisation.

Joblevel
"""

pd.crosstab(columns=[df.Attrition], index=[df.JobLevel], margins=True, normalize='index')

"""Monthly Income"""

sns.catplot(data=df, kind='bar', x='Attrition', y='MonthlyIncome')

"""Note that the average income for 'No' class is quite higher and it is obvious as those earning well will certainly not be willing to exit the organisation. Similarly those employees who are probably not earning well will certainly want to change the company.

Jobsatisfaction
"""

sns.catplot(data=df, x='Attrition', col='JobSatisfaction', kind='count')

pd.crosstab(columns=[df['Attrition']], index=[df.JobSatisfaction], margins=True, normalize='index')

"""Here we see  higher values of job satisfaction( ie more a person is satisfied with his job) lesser percent of them say a 'Yes' which is quite obvious as highly contented workers will obvioulsy not like to leave the organisation.

Enviorment
"""

sns.catplot(data=df, x='Attrition', col='EnvironmentSatisfaction', kind='count')

pd.crosstab(columns=[df.Attrition], index=[df.EnvironmentSatisfaction], margins=True, normalize='index')

"""Again we can notice that the relative percent of 'No' in people with higher grade of environment satisfacftion.

Job-involvment
"""

pd.crosstab(columns=[df.Attrition], index=[df.JobInvolvement], margins=True, normalize='index')

"""Employess with higher vaue of involment in job are showing low interst in laving organisation.

Woklife Balance
"""

sns.catplot(data=df, x='Attrition', col='WorkLifeBalance', kind='count')

pd.crosstab(columns=[df.Attrition], index=[df.WorkLifeBalance], margins=True, normalize='index')

"""Again we notice a similar trend as people with better work life balance dont want to leave the organisation."""